name: PickariaKotlin
version: 1.1
api-version: 1.18
main: fr.pickaria.Main
author: Macaron, Quozul, Alina
depend: [Vault]
loadbefore: [Towny]

commands:
  money:
    description: Voir son solde bancaire
    usage: /money
    permission: pickaria.command.money
  pay:
    description: Payer un autre joueur
    usage: /pay <joueur> <montant>
  tprandom:
    description: Vous téléporte aléatoirement sur la carte
    usage: /tprandom
  baltop:
    description: Affiche la liste des joueurs les plus riches
    usage: /baltop [page]
  sethome:
    description: Créé un point de téléportation
    usage: /sethome [home]
  home:
    description: Vous téléporte à un point de téléportation
    usage: /home [home]
  delhome:
    description: Supprime un point de téléportation
    usage: /delhome [home]
