name: PickariaKotlin
version: 1.1
api-version: 1.18
main: fr.pickaria.Main
author: Macaron, Quozul
depend: [Vault]
loadbefore: [Towny]

commands:
  money:
    description: Voir son solde bancaire
    usage: /money
    permission: pickaria.command.money
  pay:
    description: Payer un autre joueur
    usage: /pay <joueur> <montant>
  job:
    description: Rejoindre ou quitter un métier
    usage: /job <join|leave|top> <métier>
  baltop:
    description: Affiche la liste des joueurs les plus riches
    usage: /baltop [page]
