name: PickariaKotlin
version: 1.1
api-version: 1.18
main: fr.pickaria.Main
author: Macaron, Quozul, Alina
depend: [Vault]
loadbefore: [Towny]

commands:
  money:
    description: Voir son solde bancaire
    usage: /money
    permission: pickaria.command.money
  pay:
    description: Payer un autre joueur
    usage: /pay <joueur> <montant>
  tprandom:
    description: Vous téléporte aléatoirement sur la carte
    usage: /tprandom
  baltop:
    description: Affiche la liste des joueurs les plus riches
    usage: /baltop [page]
  tpa:
    description: Demande de teleportation vers un joueur
    usage: /tpa <joueur>
  tpaccept:
    description: Accepter une demande de teleportation
    usage: /tpaccept
  tpdeny:
    description: Refuser une demande de teleportation
    usage: /tpdeny
  tpcancel:
    description: Annuler une demande de teleportation
    usage: /tpcancel
