name: PickariaKotlin
version: 1.1
api-version: 1.18
main: fr.pickaria.Main
author: Macaron, Quozul, Alina
depend: [Vault, Votifier, LangUtils, ProtocolLib]
loadbefore: [Towny, Essentials]

commands:
  money:
    description: Voir son solde bancaire
    usage: /money
    permission: pickaria.command.money
  pay:
    description: Payer un autre joueur
    usage: /pay <joueur> <montant>
    permission: pickaria.command.pay
  job:
    description: Rejoindre ou quitter un métier
    usage: /job <join|leave|top|menu> [métier]
    permission: pickaria.command.job
  jobs:
    description: Rejoindre ou quitter un métier
    usage: /jobs <join|leave|top|menu> [métier]
    permission: pickaria.command.job
  tprandom:
    description: Vous téléporte aléatoirement sur la carte
    usage: /tprandom
  baltop:
    description: Affiche la liste des joueurs les plus riches
    usage: /baltop [page]
    permission: pickaria.command.baltop
  vote:
    description: Affiche la liste des sites de votes
    usage: /vote
    permission: pickaria.command.vote
  sethome:
    description: Créé un point de téléportation
    usage: /sethome [home]
  home:
    description: Vous téléporte à un point de téléportation
    usage: /home [home]
  delhome:
    description: Supprime un point de téléportation
    usage: /delhome [home]
  tpa:
    description: Demande de teleportation vers un joueur
    usage: /tpa <joueur>
  tpahere:
    description: Demande de teleportation d'un joueur sur vous
    usage: /tpahere <joueur>
  tpaccept:
    description: Accepter une demande de teleportation
    usage: /tpaccept
    aliases:
      - tpoui
      - tpyes
  tpdeny:
    description: Refuser une demande de teleportation
    usage: /tpdeny
    aliases:
      - tpno
      - tpnon
  tpcancel:
    description: Annuler une demande de teleportation
    usage: /tpcancel
