name: Pickaria
version: 1.0
api-version: 1.18
main: fr.pickaria.Main
author: Macaron, Quozul, Alina
softdepend: [Vault]
commands:
  lol:
    description: Pour rire
    usage: /<command>
  money:
    description: Voir son solde bancaire
    usage: /money
  pay:
    description: Payer un autre joueur
    usage: /pay <joueur> <montant>
  tprandom:
    description: Vous téléporte aléatoirement sur la carte
    usage: /tprandom